### ISSUE TITLE
Game scan issue with latest launcher 3.8.0.0

### ISSUE THREAD

**Issue by RebornZA** [ProjectCeleste/Celeste.Launcher#100]
# Describe the bug

When I try to launch and game scan I get this in logs:

2023-03-06 22:27:11.054 +00:00 [ERR] The system cannot find the path specified
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the path specified
   at Celeste_Public_Api.Helpers.Misc.GetRealPath(String path) in D:\a\1\s\Libs\Celeste_Public_Api\Helpers\Misc.cs:line 171
   at CelesteGameScannerUI.GameScannerWindow.SetupScenarioSymlink() in D:\a\1\s\CelesteGameScannerUI\GameScannerWindow.xaml.cs:line 117
   at CelesteGameScannerUI.GameScannerWindow.<Window_Loaded>d__8.MoveNext() in D:\a\1\s\CelesteGameScannerUI\GameScannerWindow.xaml.cs:line 71

## Steps to reproduce

Run Game Scan.

## Expected behavior

Game scan used to run on 3.6.0.0 now I get this error once I updated 3.8.0.0.

**Comment by RebornZA** [comment]
Clean install fixed issue.
